(*
 Autogenerated by Thrift Compiler (0.9.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
module ConsistencyLevel : 
sig
  type t = 
    | ONE
    | QUORUM
    | LOCAL_QUORUM
    | EACH_QUORUM
    | ALL
    | ANY
    | TWO
    | THREE
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module IndexOperator : 
sig
  type t = 
    | EQ
    | GTE
    | GT
    | LTE
    | LT
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module IndexType : 
sig
  type t = 
    | KEYS
    | CUSTOM
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module Compression : 
sig
  type t = 
    | GZIP
    | NONE
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
module CqlResultType : 
sig
  type t = 
    | ROWS
    | VOID
    | INT
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
class column :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method get_timestamp : Int64.t option
  method grab_timestamp : Int64.t
  method set_timestamp : Int64.t -> unit
  method unset_timestamp : unit
  method reset_timestamp : unit
  method get_ttl : Int32.t option
  method grab_ttl : Int32.t
  method set_ttl : Int32.t -> unit
  method unset_ttl : unit
  method reset_ttl : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_column : Protocol.t -> column
class superColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_columns : column list option
  method grab_columns : column list
  method set_columns : column list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_superColumn : Protocol.t -> superColumn
class counterColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_value : Int64.t option
  method grab_value : Int64.t
  method set_value : Int64.t -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_counterColumn : Protocol.t -> counterColumn
class counterSuperColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_columns : counterColumn list option
  method grab_columns : counterColumn list
  method set_columns : counterColumn list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_counterSuperColumn : Protocol.t -> counterSuperColumn
class columnOrSuperColumn :
object ('a)
  method get_column : column option
  method grab_column : column
  method set_column : column -> unit
  method unset_column : unit
  method reset_column : unit
  method get_super_column : superColumn option
  method grab_super_column : superColumn
  method set_super_column : superColumn -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_counter_column : counterColumn option
  method grab_counter_column : counterColumn
  method set_counter_column : counterColumn -> unit
  method unset_counter_column : unit
  method reset_counter_column : unit
  method get_counter_super_column : counterSuperColumn option
  method grab_counter_super_column : counterSuperColumn
  method set_counter_super_column : counterSuperColumn -> unit
  method unset_counter_super_column : unit
  method reset_counter_super_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnOrSuperColumn : Protocol.t -> columnOrSuperColumn
class columnParent :
object ('a)
  method get_column_family : string option
  method grab_column_family : string
  method set_column_family : string -> unit
  method unset_column_family : unit
  method reset_column_family : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnParent : Protocol.t -> columnParent
class columnPath :
object ('a)
  method get_column_family : string option
  method grab_column_family : string
  method set_column_family : string -> unit
  method unset_column_family : unit
  method reset_column_family : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_column : string option
  method grab_column : string
  method set_column : string -> unit
  method unset_column : unit
  method reset_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnPath : Protocol.t -> columnPath
class sliceRange :
object ('a)
  method get_start : string option
  method grab_start : string
  method set_start : string -> unit
  method unset_start : unit
  method reset_start : unit
  method get_finish : string option
  method grab_finish : string
  method set_finish : string -> unit
  method unset_finish : unit
  method reset_finish : unit
  method get_reversed : bool option
  method grab_reversed : bool
  method set_reversed : bool -> unit
  method reset_reversed : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_sliceRange : Protocol.t -> sliceRange
class slicePredicate :
object ('a)
  method get_column_names : string list option
  method grab_column_names : string list
  method set_column_names : string list -> unit
  method unset_column_names : unit
  method reset_column_names : unit
  method get_slice_range : sliceRange option
  method grab_slice_range : sliceRange
  method set_slice_range : sliceRange -> unit
  method unset_slice_range : unit
  method reset_slice_range : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_slicePredicate : Protocol.t -> slicePredicate
class indexExpression :
object ('a)
  method get_column_name : string option
  method grab_column_name : string
  method set_column_name : string -> unit
  method unset_column_name : unit
  method reset_column_name : unit
  method get_op : IndexOperator.t option
  method grab_op : IndexOperator.t
  method set_op : IndexOperator.t -> unit
  method unset_op : unit
  method reset_op : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_indexExpression : Protocol.t -> indexExpression
class indexClause :
object ('a)
  method get_expressions : indexExpression list option
  method grab_expressions : indexExpression list
  method set_expressions : indexExpression list -> unit
  method unset_expressions : unit
  method reset_expressions : unit
  method get_start_key : string option
  method grab_start_key : string
  method set_start_key : string -> unit
  method unset_start_key : unit
  method reset_start_key : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_indexClause : Protocol.t -> indexClause
class keyRange :
object ('a)
  method get_start_key : string option
  method grab_start_key : string
  method set_start_key : string -> unit
  method unset_start_key : unit
  method reset_start_key : unit
  method get_end_key : string option
  method grab_end_key : string
  method set_end_key : string -> unit
  method unset_end_key : unit
  method reset_end_key : unit
  method get_start_token : string option
  method grab_start_token : string
  method set_start_token : string -> unit
  method unset_start_token : unit
  method reset_start_token : unit
  method get_end_token : string option
  method grab_end_token : string
  method set_end_token : string -> unit
  method unset_end_token : unit
  method reset_end_token : unit
  method get_row_filter : indexExpression list option
  method grab_row_filter : indexExpression list
  method set_row_filter : indexExpression list -> unit
  method unset_row_filter : unit
  method reset_row_filter : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keyRange : Protocol.t -> keyRange
class keySlice :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_columns : columnOrSuperColumn list option
  method grab_columns : columnOrSuperColumn list
  method set_columns : columnOrSuperColumn list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keySlice : Protocol.t -> keySlice
class keyCount :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method unset_count : unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keyCount : Protocol.t -> keyCount
class deletion :
object ('a)
  method get_timestamp : Int64.t option
  method grab_timestamp : Int64.t
  method set_timestamp : Int64.t -> unit
  method unset_timestamp : unit
  method reset_timestamp : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_predicate : slicePredicate option
  method grab_predicate : slicePredicate
  method set_predicate : slicePredicate -> unit
  method unset_predicate : unit
  method reset_predicate : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_deletion : Protocol.t -> deletion
class mutation :
object ('a)
  method get_column_or_supercolumn : columnOrSuperColumn option
  method grab_column_or_supercolumn : columnOrSuperColumn
  method set_column_or_supercolumn : columnOrSuperColumn -> unit
  method unset_column_or_supercolumn : unit
  method reset_column_or_supercolumn : unit
  method get_deletion : deletion option
  method grab_deletion : deletion
  method set_deletion : deletion -> unit
  method unset_deletion : unit
  method reset_deletion : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_mutation : Protocol.t -> mutation
class endpointDetails :
object ('a)
  method get_host : string option
  method grab_host : string
  method set_host : string -> unit
  method unset_host : unit
  method reset_host : unit
  method get_datacenter : string option
  method grab_datacenter : string
  method set_datacenter : string -> unit
  method unset_datacenter : unit
  method reset_datacenter : unit
  method get_rack : string option
  method grab_rack : string
  method set_rack : string -> unit
  method unset_rack : unit
  method reset_rack : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_endpointDetails : Protocol.t -> endpointDetails
class tokenRange :
object ('a)
  method get_start_token : string option
  method grab_start_token : string
  method set_start_token : string -> unit
  method unset_start_token : unit
  method reset_start_token : unit
  method get_end_token : string option
  method grab_end_token : string
  method set_end_token : string -> unit
  method unset_end_token : unit
  method reset_end_token : unit
  method get_endpoints : string list option
  method grab_endpoints : string list
  method set_endpoints : string list -> unit
  method unset_endpoints : unit
  method reset_endpoints : unit
  method get_rpc_endpoints : string list option
  method grab_rpc_endpoints : string list
  method set_rpc_endpoints : string list -> unit
  method unset_rpc_endpoints : unit
  method reset_rpc_endpoints : unit
  method get_endpoint_details : endpointDetails list option
  method grab_endpoint_details : endpointDetails list
  method set_endpoint_details : endpointDetails list -> unit
  method unset_endpoint_details : unit
  method reset_endpoint_details : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_tokenRange : Protocol.t -> tokenRange
class authenticationRequest :
object ('a)
  method get_credentials : (string,string) Hashtbl.t option
  method grab_credentials : (string,string) Hashtbl.t
  method set_credentials : (string,string) Hashtbl.t -> unit
  method unset_credentials : unit
  method reset_credentials : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_authenticationRequest : Protocol.t -> authenticationRequest
class columnDef :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_validation_class : string option
  method grab_validation_class : string
  method set_validation_class : string -> unit
  method unset_validation_class : unit
  method reset_validation_class : unit
  method get_index_type : IndexType.t option
  method grab_index_type : IndexType.t
  method set_index_type : IndexType.t -> unit
  method unset_index_type : unit
  method reset_index_type : unit
  method get_index_name : string option
  method grab_index_name : string
  method set_index_name : string -> unit
  method unset_index_name : unit
  method reset_index_name : unit
  method get_index_options : (string,string) Hashtbl.t option
  method grab_index_options : (string,string) Hashtbl.t
  method set_index_options : (string,string) Hashtbl.t -> unit
  method unset_index_options : unit
  method reset_index_options : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnDef : Protocol.t -> columnDef
class cfDef :
object ('a)
  method get_keyspace : string option
  method grab_keyspace : string
  method set_keyspace : string -> unit
  method unset_keyspace : unit
  method reset_keyspace : unit
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_column_type : string option
  method grab_column_type : string
  method set_column_type : string -> unit
  method reset_column_type : unit
  method get_comparator_type : string option
  method grab_comparator_type : string
  method set_comparator_type : string -> unit
  method reset_comparator_type : unit
  method get_subcomparator_type : string option
  method grab_subcomparator_type : string
  method set_subcomparator_type : string -> unit
  method unset_subcomparator_type : unit
  method reset_subcomparator_type : unit
  method get_comment : string option
  method grab_comment : string
  method set_comment : string -> unit
  method unset_comment : unit
  method reset_comment : unit
  method get_read_repair_chance : float option
  method grab_read_repair_chance : float
  method set_read_repair_chance : float -> unit
  method unset_read_repair_chance : unit
  method reset_read_repair_chance : unit
  method get_column_metadata : columnDef list option
  method grab_column_metadata : columnDef list
  method set_column_metadata : columnDef list -> unit
  method unset_column_metadata : unit
  method reset_column_metadata : unit
  method get_gc_grace_seconds : Int32.t option
  method grab_gc_grace_seconds : Int32.t
  method set_gc_grace_seconds : Int32.t -> unit
  method unset_gc_grace_seconds : unit
  method reset_gc_grace_seconds : unit
  method get_default_validation_class : string option
  method grab_default_validation_class : string
  method set_default_validation_class : string -> unit
  method unset_default_validation_class : unit
  method reset_default_validation_class : unit
  method get_id : Int32.t option
  method grab_id : Int32.t
  method set_id : Int32.t -> unit
  method unset_id : unit
  method reset_id : unit
  method get_min_compaction_threshold : Int32.t option
  method grab_min_compaction_threshold : Int32.t
  method set_min_compaction_threshold : Int32.t -> unit
  method unset_min_compaction_threshold : unit
  method reset_min_compaction_threshold : unit
  method get_max_compaction_threshold : Int32.t option
  method grab_max_compaction_threshold : Int32.t
  method set_max_compaction_threshold : Int32.t -> unit
  method unset_max_compaction_threshold : unit
  method reset_max_compaction_threshold : unit
  method get_replicate_on_write : bool option
  method grab_replicate_on_write : bool
  method set_replicate_on_write : bool -> unit
  method unset_replicate_on_write : unit
  method reset_replicate_on_write : unit
  method get_key_validation_class : string option
  method grab_key_validation_class : string
  method set_key_validation_class : string -> unit
  method unset_key_validation_class : unit
  method reset_key_validation_class : unit
  method get_key_alias : string option
  method grab_key_alias : string
  method set_key_alias : string -> unit
  method unset_key_alias : unit
  method reset_key_alias : unit
  method get_compaction_strategy : string option
  method grab_compaction_strategy : string
  method set_compaction_strategy : string -> unit
  method unset_compaction_strategy : unit
  method reset_compaction_strategy : unit
  method get_compaction_strategy_options : (string,string) Hashtbl.t option
  method grab_compaction_strategy_options : (string,string) Hashtbl.t
  method set_compaction_strategy_options : (string,string) Hashtbl.t -> unit
  method unset_compaction_strategy_options : unit
  method reset_compaction_strategy_options : unit
  method get_compression_options : (string,string) Hashtbl.t option
  method grab_compression_options : (string,string) Hashtbl.t
  method set_compression_options : (string,string) Hashtbl.t -> unit
  method unset_compression_options : unit
  method reset_compression_options : unit
  method get_bloom_filter_fp_chance : float option
  method grab_bloom_filter_fp_chance : float
  method set_bloom_filter_fp_chance : float -> unit
  method unset_bloom_filter_fp_chance : unit
  method reset_bloom_filter_fp_chance : unit
  method get_caching : string option
  method grab_caching : string
  method set_caching : string -> unit
  method reset_caching : unit
  method get_dclocal_read_repair_chance : float option
  method grab_dclocal_read_repair_chance : float
  method set_dclocal_read_repair_chance : float -> unit
  method reset_dclocal_read_repair_chance : unit
  method get_row_cache_size : float option
  method grab_row_cache_size : float
  method set_row_cache_size : float -> unit
  method unset_row_cache_size : unit
  method reset_row_cache_size : unit
  method get_key_cache_size : float option
  method grab_key_cache_size : float
  method set_key_cache_size : float -> unit
  method unset_key_cache_size : unit
  method reset_key_cache_size : unit
  method get_row_cache_save_period_in_seconds : Int32.t option
  method grab_row_cache_save_period_in_seconds : Int32.t
  method set_row_cache_save_period_in_seconds : Int32.t -> unit
  method unset_row_cache_save_period_in_seconds : unit
  method reset_row_cache_save_period_in_seconds : unit
  method get_key_cache_save_period_in_seconds : Int32.t option
  method grab_key_cache_save_period_in_seconds : Int32.t
  method set_key_cache_save_period_in_seconds : Int32.t -> unit
  method unset_key_cache_save_period_in_seconds : unit
  method reset_key_cache_save_period_in_seconds : unit
  method get_memtable_flush_after_mins : Int32.t option
  method grab_memtable_flush_after_mins : Int32.t
  method set_memtable_flush_after_mins : Int32.t -> unit
  method unset_memtable_flush_after_mins : unit
  method reset_memtable_flush_after_mins : unit
  method get_memtable_throughput_in_mb : Int32.t option
  method grab_memtable_throughput_in_mb : Int32.t
  method set_memtable_throughput_in_mb : Int32.t -> unit
  method unset_memtable_throughput_in_mb : unit
  method reset_memtable_throughput_in_mb : unit
  method get_memtable_operations_in_millions : float option
  method grab_memtable_operations_in_millions : float
  method set_memtable_operations_in_millions : float -> unit
  method unset_memtable_operations_in_millions : unit
  method reset_memtable_operations_in_millions : unit
  method get_merge_shards_chance : float option
  method grab_merge_shards_chance : float
  method set_merge_shards_chance : float -> unit
  method unset_merge_shards_chance : unit
  method reset_merge_shards_chance : unit
  method get_row_cache_provider : string option
  method grab_row_cache_provider : string
  method set_row_cache_provider : string -> unit
  method unset_row_cache_provider : unit
  method reset_row_cache_provider : unit
  method get_row_cache_keys_to_save : Int32.t option
  method grab_row_cache_keys_to_save : Int32.t
  method set_row_cache_keys_to_save : Int32.t -> unit
  method unset_row_cache_keys_to_save : unit
  method reset_row_cache_keys_to_save : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cfDef : Protocol.t -> cfDef
class ksDef :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_strategy_class : string option
  method grab_strategy_class : string
  method set_strategy_class : string -> unit
  method unset_strategy_class : unit
  method reset_strategy_class : unit
  method get_strategy_options : (string,string) Hashtbl.t option
  method grab_strategy_options : (string,string) Hashtbl.t
  method set_strategy_options : (string,string) Hashtbl.t -> unit
  method unset_strategy_options : unit
  method reset_strategy_options : unit
  method get_replication_factor : Int32.t option
  method grab_replication_factor : Int32.t
  method set_replication_factor : Int32.t -> unit
  method unset_replication_factor : unit
  method reset_replication_factor : unit
  method get_cf_defs : cfDef list option
  method grab_cf_defs : cfDef list
  method set_cf_defs : cfDef list -> unit
  method unset_cf_defs : unit
  method reset_cf_defs : unit
  method get_durable_writes : bool option
  method grab_durable_writes : bool
  method set_durable_writes : bool -> unit
  method reset_durable_writes : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_ksDef : Protocol.t -> ksDef
class cqlRow :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_columns : column list option
  method grab_columns : column list
  method set_columns : column list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlRow : Protocol.t -> cqlRow
class cqlMetadata :
object ('a)
  method get_name_types : (string,string) Hashtbl.t option
  method grab_name_types : (string,string) Hashtbl.t
  method set_name_types : (string,string) Hashtbl.t -> unit
  method unset_name_types : unit
  method reset_name_types : unit
  method get_value_types : (string,string) Hashtbl.t option
  method grab_value_types : (string,string) Hashtbl.t
  method set_value_types : (string,string) Hashtbl.t -> unit
  method unset_value_types : unit
  method reset_value_types : unit
  method get_default_name_type : string option
  method grab_default_name_type : string
  method set_default_name_type : string -> unit
  method unset_default_name_type : unit
  method reset_default_name_type : unit
  method get_default_value_type : string option
  method grab_default_value_type : string
  method set_default_value_type : string -> unit
  method unset_default_value_type : unit
  method reset_default_value_type : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlMetadata : Protocol.t -> cqlMetadata
class cqlResult :
object ('a)
  method get_type : CqlResultType.t option
  method grab_type : CqlResultType.t
  method set_type : CqlResultType.t -> unit
  method unset_type : unit
  method reset_type : unit
  method get_rows : cqlRow list option
  method grab_rows : cqlRow list
  method set_rows : cqlRow list -> unit
  method unset_rows : unit
  method reset_rows : unit
  method get_num : Int32.t option
  method grab_num : Int32.t
  method set_num : Int32.t -> unit
  method unset_num : unit
  method reset_num : unit
  method get_schema : cqlMetadata option
  method grab_schema : cqlMetadata
  method set_schema : cqlMetadata -> unit
  method unset_schema : unit
  method reset_schema : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlResult : Protocol.t -> cqlResult
class cqlPreparedResult :
object ('a)
  method get_itemId : Int32.t option
  method grab_itemId : Int32.t
  method set_itemId : Int32.t -> unit
  method unset_itemId : unit
  method reset_itemId : unit
  method get_count : Int32.t option
  method grab_count : Int32.t
  method set_count : Int32.t -> unit
  method unset_count : unit
  method reset_count : unit
  method get_variable_types : string list option
  method grab_variable_types : string list
  method set_variable_types : string list -> unit
  method unset_variable_types : unit
  method reset_variable_types : unit
  method get_variable_names : string list option
  method grab_variable_names : string list
  method set_variable_names : string list -> unit
  method unset_variable_names : unit
  method reset_variable_names : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlPreparedResult : Protocol.t -> cqlPreparedResult
class notFoundException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception NotFoundException of notFoundException
val read_notFoundException : Protocol.t -> notFoundException
class invalidRequestException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception InvalidRequestException of invalidRequestException
val read_invalidRequestException : Protocol.t -> invalidRequestException
class unavailableException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception UnavailableException of unavailableException
val read_unavailableException : Protocol.t -> unavailableException
class timedOutException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception TimedOutException of timedOutException
val read_timedOutException : Protocol.t -> timedOutException
class authenticationException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception AuthenticationException of authenticationException
val read_authenticationException : Protocol.t -> authenticationException
class authorizationException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception AuthorizationException of authorizationException
val read_authorizationException : Protocol.t -> authorizationException
class schemaDisagreementException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception SchemaDisagreementException of schemaDisagreementException
val read_schemaDisagreementException : Protocol.t -> schemaDisagreementException
