(*
 Autogenerated by Thrift

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
module ConsistencyLevel : 
sig
  type t = 
    | ONE
    | QUORUM
    | LOCAL_QUORUM
    | EACH_QUORUM
    | ALL
    | ANY
    | TWO
    | THREE
  val to_i : t -> int
  val of_i : int -> t
end
module IndexOperator : 
sig
  type t = 
    | EQ
    | GTE
    | GT
    | LTE
    | LT
  val to_i : t -> int
  val of_i : int -> t
end
module IndexType : 
sig
  type t = 
    | KEYS
  val to_i : t -> int
  val of_i : int -> t
end
module Compression : 
sig
  type t = 
    | GZIP
    | NONE
  val to_i : t -> int
  val of_i : int -> t
end
module CqlResultType : 
sig
  type t = 
    | ROWS
    | VOID
    | INT
  val to_i : t -> int
  val of_i : int -> t
end
class column :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method get_timestamp : Int64.t option
  method grab_timestamp : Int64.t
  method set_timestamp : Int64.t -> unit
  method unset_timestamp : unit
  method reset_timestamp : unit
  method get_ttl : int option
  method grab_ttl : int
  method set_ttl : int -> unit
  method unset_ttl : unit
  method reset_ttl : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_column : Protocol.t -> column
class superColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_columns : column list option
  method grab_columns : column list
  method set_columns : column list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_superColumn : Protocol.t -> superColumn
class counterColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_value : Int64.t option
  method grab_value : Int64.t
  method set_value : Int64.t -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_counterColumn : Protocol.t -> counterColumn
class counterSuperColumn :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_columns : counterColumn list option
  method grab_columns : counterColumn list
  method set_columns : counterColumn list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_counterSuperColumn : Protocol.t -> counterSuperColumn
class columnOrSuperColumn :
object ('a)
  method get_column : column option
  method grab_column : column
  method set_column : column -> unit
  method unset_column : unit
  method reset_column : unit
  method get_super_column : superColumn option
  method grab_super_column : superColumn
  method set_super_column : superColumn -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_counter_column : counterColumn option
  method grab_counter_column : counterColumn
  method set_counter_column : counterColumn -> unit
  method unset_counter_column : unit
  method reset_counter_column : unit
  method get_counter_super_column : counterSuperColumn option
  method grab_counter_super_column : counterSuperColumn
  method set_counter_super_column : counterSuperColumn -> unit
  method unset_counter_super_column : unit
  method reset_counter_super_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnOrSuperColumn : Protocol.t -> columnOrSuperColumn
class columnParent :
object ('a)
  method get_column_family : string option
  method grab_column_family : string
  method set_column_family : string -> unit
  method unset_column_family : unit
  method reset_column_family : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnParent : Protocol.t -> columnParent
class columnPath :
object ('a)
  method get_column_family : string option
  method grab_column_family : string
  method set_column_family : string -> unit
  method unset_column_family : unit
  method reset_column_family : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_column : string option
  method grab_column : string
  method set_column : string -> unit
  method unset_column : unit
  method reset_column : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnPath : Protocol.t -> columnPath
class sliceRange :
object ('a)
  method get_start : string option
  method grab_start : string
  method set_start : string -> unit
  method unset_start : unit
  method reset_start : unit
  method get_finish : string option
  method grab_finish : string
  method set_finish : string -> unit
  method unset_finish : unit
  method reset_finish : unit
  method get_reversed : bool option
  method grab_reversed : bool
  method set_reversed : bool -> unit
  method reset_reversed : unit
  method get_count : int option
  method grab_count : int
  method set_count : int -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_sliceRange : Protocol.t -> sliceRange
class slicePredicate :
object ('a)
  method get_column_names : string list option
  method grab_column_names : string list
  method set_column_names : string list -> unit
  method unset_column_names : unit
  method reset_column_names : unit
  method get_slice_range : sliceRange option
  method grab_slice_range : sliceRange
  method set_slice_range : sliceRange -> unit
  method unset_slice_range : unit
  method reset_slice_range : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_slicePredicate : Protocol.t -> slicePredicate
class indexExpression :
object ('a)
  method get_column_name : string option
  method grab_column_name : string
  method set_column_name : string -> unit
  method unset_column_name : unit
  method reset_column_name : unit
  method get_op : IndexOperator.t option
  method grab_op : IndexOperator.t
  method set_op : IndexOperator.t -> unit
  method unset_op : unit
  method reset_op : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_indexExpression : Protocol.t -> indexExpression
class indexClause :
object ('a)
  method get_expressions : indexExpression list option
  method grab_expressions : indexExpression list
  method set_expressions : indexExpression list -> unit
  method unset_expressions : unit
  method reset_expressions : unit
  method get_start_key : string option
  method grab_start_key : string
  method set_start_key : string -> unit
  method unset_start_key : unit
  method reset_start_key : unit
  method get_count : int option
  method grab_count : int
  method set_count : int -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_indexClause : Protocol.t -> indexClause
class keyRange :
object ('a)
  method get_start_key : string option
  method grab_start_key : string
  method set_start_key : string -> unit
  method unset_start_key : unit
  method reset_start_key : unit
  method get_end_key : string option
  method grab_end_key : string
  method set_end_key : string -> unit
  method unset_end_key : unit
  method reset_end_key : unit
  method get_start_token : string option
  method grab_start_token : string
  method set_start_token : string -> unit
  method unset_start_token : unit
  method reset_start_token : unit
  method get_end_token : string option
  method grab_end_token : string
  method set_end_token : string -> unit
  method unset_end_token : unit
  method reset_end_token : unit
  method get_count : int option
  method grab_count : int
  method set_count : int -> unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keyRange : Protocol.t -> keyRange
class keySlice :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_columns : columnOrSuperColumn list option
  method grab_columns : columnOrSuperColumn list
  method set_columns : columnOrSuperColumn list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keySlice : Protocol.t -> keySlice
class keyCount :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_count : int option
  method grab_count : int
  method set_count : int -> unit
  method unset_count : unit
  method reset_count : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_keyCount : Protocol.t -> keyCount
class deletion :
object ('a)
  method get_timestamp : Int64.t option
  method grab_timestamp : Int64.t
  method set_timestamp : Int64.t -> unit
  method unset_timestamp : unit
  method reset_timestamp : unit
  method get_super_column : string option
  method grab_super_column : string
  method set_super_column : string -> unit
  method unset_super_column : unit
  method reset_super_column : unit
  method get_predicate : slicePredicate option
  method grab_predicate : slicePredicate
  method set_predicate : slicePredicate -> unit
  method unset_predicate : unit
  method reset_predicate : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_deletion : Protocol.t -> deletion
class mutation :
object ('a)
  method get_column_or_supercolumn : columnOrSuperColumn option
  method grab_column_or_supercolumn : columnOrSuperColumn
  method set_column_or_supercolumn : columnOrSuperColumn -> unit
  method unset_column_or_supercolumn : unit
  method reset_column_or_supercolumn : unit
  method get_deletion : deletion option
  method grab_deletion : deletion
  method set_deletion : deletion -> unit
  method unset_deletion : unit
  method reset_deletion : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_mutation : Protocol.t -> mutation
class tokenRange :
object ('a)
  method get_start_token : string option
  method grab_start_token : string
  method set_start_token : string -> unit
  method unset_start_token : unit
  method reset_start_token : unit
  method get_end_token : string option
  method grab_end_token : string
  method set_end_token : string -> unit
  method unset_end_token : unit
  method reset_end_token : unit
  method get_endpoints : string list option
  method grab_endpoints : string list
  method set_endpoints : string list -> unit
  method unset_endpoints : unit
  method reset_endpoints : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_tokenRange : Protocol.t -> tokenRange
class authenticationRequest :
object ('a)
  method get_credentials : (string,string) Hashtbl.t option
  method grab_credentials : (string,string) Hashtbl.t
  method set_credentials : (string,string) Hashtbl.t -> unit
  method unset_credentials : unit
  method reset_credentials : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_authenticationRequest : Protocol.t -> authenticationRequest
class columnDef :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_validation_class : string option
  method grab_validation_class : string
  method set_validation_class : string -> unit
  method unset_validation_class : unit
  method reset_validation_class : unit
  method get_index_type : IndexType.t option
  method grab_index_type : IndexType.t
  method set_index_type : IndexType.t -> unit
  method unset_index_type : unit
  method reset_index_type : unit
  method get_index_name : string option
  method grab_index_name : string
  method set_index_name : string -> unit
  method unset_index_name : unit
  method reset_index_name : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_columnDef : Protocol.t -> columnDef
class cfDef :
object ('a)
  method get_keyspace : string option
  method grab_keyspace : string
  method set_keyspace : string -> unit
  method unset_keyspace : unit
  method reset_keyspace : unit
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_column_type : string option
  method grab_column_type : string
  method set_column_type : string -> unit
  method reset_column_type : unit
  method get_comparator_type : string option
  method grab_comparator_type : string
  method set_comparator_type : string -> unit
  method reset_comparator_type : unit
  method get_subcomparator_type : string option
  method grab_subcomparator_type : string
  method set_subcomparator_type : string -> unit
  method unset_subcomparator_type : unit
  method reset_subcomparator_type : unit
  method get_comment : string option
  method grab_comment : string
  method set_comment : string -> unit
  method unset_comment : unit
  method reset_comment : unit
  method get_row_cache_size : float option
  method grab_row_cache_size : float
  method set_row_cache_size : float -> unit
  method reset_row_cache_size : unit
  method get_key_cache_size : float option
  method grab_key_cache_size : float
  method set_key_cache_size : float -> unit
  method reset_key_cache_size : unit
  method get_read_repair_chance : float option
  method grab_read_repair_chance : float
  method set_read_repair_chance : float -> unit
  method reset_read_repair_chance : unit
  method get_column_metadata : columnDef list option
  method grab_column_metadata : columnDef list
  method set_column_metadata : columnDef list -> unit
  method unset_column_metadata : unit
  method reset_column_metadata : unit
  method get_gc_grace_seconds : int option
  method grab_gc_grace_seconds : int
  method set_gc_grace_seconds : int -> unit
  method unset_gc_grace_seconds : unit
  method reset_gc_grace_seconds : unit
  method get_default_validation_class : string option
  method grab_default_validation_class : string
  method set_default_validation_class : string -> unit
  method unset_default_validation_class : unit
  method reset_default_validation_class : unit
  method get_id : int option
  method grab_id : int
  method set_id : int -> unit
  method unset_id : unit
  method reset_id : unit
  method get_min_compaction_threshold : int option
  method grab_min_compaction_threshold : int
  method set_min_compaction_threshold : int -> unit
  method unset_min_compaction_threshold : unit
  method reset_min_compaction_threshold : unit
  method get_max_compaction_threshold : int option
  method grab_max_compaction_threshold : int
  method set_max_compaction_threshold : int -> unit
  method unset_max_compaction_threshold : unit
  method reset_max_compaction_threshold : unit
  method get_row_cache_save_period_in_seconds : int option
  method grab_row_cache_save_period_in_seconds : int
  method set_row_cache_save_period_in_seconds : int -> unit
  method unset_row_cache_save_period_in_seconds : unit
  method reset_row_cache_save_period_in_seconds : unit
  method get_key_cache_save_period_in_seconds : int option
  method grab_key_cache_save_period_in_seconds : int
  method set_key_cache_save_period_in_seconds : int -> unit
  method unset_key_cache_save_period_in_seconds : unit
  method reset_key_cache_save_period_in_seconds : unit
  method get_memtable_flush_after_mins : int option
  method grab_memtable_flush_after_mins : int
  method set_memtable_flush_after_mins : int -> unit
  method unset_memtable_flush_after_mins : unit
  method reset_memtable_flush_after_mins : unit
  method get_memtable_throughput_in_mb : int option
  method grab_memtable_throughput_in_mb : int
  method set_memtable_throughput_in_mb : int -> unit
  method unset_memtable_throughput_in_mb : unit
  method reset_memtable_throughput_in_mb : unit
  method get_memtable_operations_in_millions : float option
  method grab_memtable_operations_in_millions : float
  method set_memtable_operations_in_millions : float -> unit
  method unset_memtable_operations_in_millions : unit
  method reset_memtable_operations_in_millions : unit
  method get_replicate_on_write : bool option
  method grab_replicate_on_write : bool
  method set_replicate_on_write : bool -> unit
  method unset_replicate_on_write : unit
  method reset_replicate_on_write : unit
  method get_merge_shards_chance : float option
  method grab_merge_shards_chance : float
  method set_merge_shards_chance : float -> unit
  method unset_merge_shards_chance : unit
  method reset_merge_shards_chance : unit
  method get_key_validation_class : string option
  method grab_key_validation_class : string
  method set_key_validation_class : string -> unit
  method unset_key_validation_class : unit
  method reset_key_validation_class : unit
  method get_row_cache_provider : string option
  method grab_row_cache_provider : string
  method set_row_cache_provider : string -> unit
  method reset_row_cache_provider : unit
  method get_key_alias : string option
  method grab_key_alias : string
  method set_key_alias : string -> unit
  method unset_key_alias : unit
  method reset_key_alias : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cfDef : Protocol.t -> cfDef
class ksDef :
object ('a)
  method get_name : string option
  method grab_name : string
  method set_name : string -> unit
  method unset_name : unit
  method reset_name : unit
  method get_strategy_class : string option
  method grab_strategy_class : string
  method set_strategy_class : string -> unit
  method unset_strategy_class : unit
  method reset_strategy_class : unit
  method get_strategy_options : (string,string) Hashtbl.t option
  method grab_strategy_options : (string,string) Hashtbl.t
  method set_strategy_options : (string,string) Hashtbl.t -> unit
  method unset_strategy_options : unit
  method reset_strategy_options : unit
  method get_replication_factor : int option
  method grab_replication_factor : int
  method set_replication_factor : int -> unit
  method unset_replication_factor : unit
  method reset_replication_factor : unit
  method get_cf_defs : cfDef list option
  method grab_cf_defs : cfDef list
  method set_cf_defs : cfDef list -> unit
  method unset_cf_defs : unit
  method reset_cf_defs : unit
  method get_durable_writes : bool option
  method grab_durable_writes : bool
  method set_durable_writes : bool -> unit
  method reset_durable_writes : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_ksDef : Protocol.t -> ksDef
class cqlRow :
object ('a)
  method get_key : string option
  method grab_key : string
  method set_key : string -> unit
  method unset_key : unit
  method reset_key : unit
  method get_columns : column list option
  method grab_columns : column list
  method set_columns : column list -> unit
  method unset_columns : unit
  method reset_columns : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlRow : Protocol.t -> cqlRow
class cqlResult :
object ('a)
  method get_type : CqlResultType.t option
  method grab_type : CqlResultType.t
  method set_type : CqlResultType.t -> unit
  method unset_type : unit
  method reset_type : unit
  method get_rows : cqlRow list option
  method grab_rows : cqlRow list
  method set_rows : cqlRow list -> unit
  method unset_rows : unit
  method reset_rows : unit
  method get_num : int option
  method grab_num : int
  method set_num : int -> unit
  method unset_num : unit
  method reset_num : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_cqlResult : Protocol.t -> cqlResult
class notFoundException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception NotFoundException of notFoundException
val read_notFoundException : Protocol.t -> notFoundException
class invalidRequestException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception InvalidRequestException of invalidRequestException
val read_invalidRequestException : Protocol.t -> invalidRequestException
class unavailableException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception UnavailableException of unavailableException
val read_unavailableException : Protocol.t -> unavailableException
class timedOutException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception TimedOutException of timedOutException
val read_timedOutException : Protocol.t -> timedOutException
class authenticationException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception AuthenticationException of authenticationException
val read_authenticationException : Protocol.t -> authenticationException
class authorizationException :
object ('a)
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception AuthorizationException of authorizationException
val read_authorizationException : Protocol.t -> authorizationException
class schemaDisagreementException :
object ('a)
  method copy : 'a
  method write : Protocol.t -> unit
end
exception SchemaDisagreementException of schemaDisagreementException
val read_schemaDisagreementException : Protocol.t -> schemaDisagreementException
